services:
  - type: web
    name: online-internship-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: online_internship_portal
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_FRONTEND_URL
        sync: false
      - key: PORT
        value: 5000
